TeamPiickle/server

.github/workflows/notion-github-issue-sync.yml, docker-compose.yml
**우선순위**
D-0
**변경사항**
- 워크플로우 파일 추가
- 도커 컴포즈 파일 추가
**유의사항**
**참조**
https://github.com/noah0316/notion-github-issue-sync
=> [CHORE] 레포지토리 이슈와 노션 데이터베이스 연동

src/models/ballotResult.ts, src/models/emailAuth.ts, src/models/user.ts
**우선순위**
D-0
**변경사항**
- closes: #8 
- 이슈 참조
**유의사항**
- 딱히 없음
**참조**
=> [FIX] 스키마 타임스탬프

src/middlewares/errorHandler.ts
**우선순위**
D-0
**변경사항**
* close #18 
**유의사항**
빠르게 approve 부탁해여
**참조**
=> [HOTFIX] ERROR HANDLER 수정

src/controllers/CategoryController.ts, src/controllers/index.ts, src/intefaces/CategoryResponseDto.ts, src/intefaces/common.ts, src/middlewares/errorHandler.ts, src/modules/responseMessage.ts, src/routes/CategoryRouter.ts, src/routes/index.ts, src/services/CategoryService.ts, src/services/index.ts
**우선순위**
D-0
**변경사항**
#11 
간편 대화주제 카테고리 리스트로 가져오는 기능입니다
**유의사항**
카테고리 아이디와 제목을 가져옵니다
**참조**
=> [FEAT] 간편 대화주제 카테고리 리스트 조회

src/middlewares/errorHandler.ts, src/modules/responseMessage.ts
**우선순위**
D-0
**변경사항**
* closes #20 
* error handler 충돌 해결
**유의사항**
**참조**
=> [CHORE] 충돌 바로잡기

src/controllers/CategoryController.ts, src/controllers/userController.ts, src/routes/userRouter.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
* closes #22 
* 로그인시 미들웨어에 auth 제거
* 비밀번호 정합성 로직 수정
**유의사항**
**참조**
=> [HOTFIX] 로그인 로직 수정

src/controllers/ballotController.ts, src/intefaces/CreateBallotResultDto.ts, src/intefaces/common.ts, src/modules/responseMessage.ts, src/routes/ballotRouter.ts, src/routes/index.ts, src/services/ballotService.ts, src/services/index.ts
**우선순위**
D-0
**변경사항**
- closes: #14 
**유의사항**
**참조**
=> [FEAT] 투표하기

src/controllers/userController.ts, src/intefaces/common.ts, src/middlewares/errorHandler.ts, src/modules/responseMessage.ts, src/routes/userRouter.ts, src/services/userService.ts
**우선순위**
D-
**변경사항**
* closes #27 
* 유저 닉네임 변경 로직 추가
* 유저 닉네임 중복 검사
**유의사항**
**참조**
=> [FEAT] 유저 닉네임 변경 API

src/controllers/CategoryController.ts, src/intefaces/CardResponseDto.ts, src/intefaces/CategoryResponseDto.ts, src/models/card.ts, src/models/category.ts, src/models/interface/ICard.ts, src/modules/responseMessage.ts, src/routes/CategoryRouter.ts, src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
Close #25  
카테고리에 있는 카드 상세 조회기능
**유의사항**
데이터를 넣을 때 주의해서 넣고 체크해주시면 감사하겠습니다!
**참조**
=> [FEAT] 카테고리별 대화 주제 리스트 조회

package.json, src/config/index.ts, src/config/multer.ts, src/config/s3Config.ts, src/controllers/userController.ts, src/intefaces/common.ts, src/intefaces/user/UserProfileImageUrlDto.ts, src/intefaces/user/UserUpdateNicknameDto.ts, src/middlewares/auth.ts, src/modules/responseMessage.ts, src/routes/userRouter.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
* closes #26 
* s3, multer 설정 추가
* 프로필 사진 수정 API 
* jwt 토큰 req 수정
**유의사항**
**참조**
=> [FEAT] 프로필 사진 수정 API

src/controllers/ballotController.ts, src/controllers/userController.ts, src/intefaces/CreateBallotResultDto.ts, src/intefaces/JwtPayloadInfo.ts, src/intefaces/common.ts, src/intefaces/user/UserUpdateNicknameDto.ts, src/middlewares/auth.ts, src/routes/userRouter.ts, src/services/ballotService.ts, src/services/userService.ts, src/types/express.d.ts
**우선순위**
D-1
**변경사항**
- closes: #41 
- 이슈 참조
**유의사항**
- 딱히 바뀐 부분은 없습니다!
- 건드린 부분은 모두 테스트 완료했습니다. (투표하기, 로그인, 닉네임변경, 프로필사진변경)
**참조**
=> [FIX] jwt 페이로드 위치 변경에 따른 기존 기능 수정

src/controllers/index.ts, src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
title만 조회에서 content까지 조회하도록 했습니다.
**유의사항**
**참조**
=> [FIX] 간편 대화주제 카테고리 리스트 조회

src/controllers/CategoryController.ts, src/modules/responseMessage.ts, src/routes/CategoryRouter.ts, src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
Close: #39 
대화주제 필터를 통해 리스트 조회합니다
**유의사항**
이유는 모르겠지만 Router에서 보면 Id를 넣는 곳이 있는데 아무ID를 넣어도 잘 작동합니다 근데 없으면 안돌아갑니다. 이유를 안다면 코드리뷰 부탁드립니다.
**참조**
윤가영
=> [FEAT] 대화주제 추천 리스트 조회

src/intefaces/CardResponseDto.ts, src/intefaces/CategoryResponseDto.ts, src/models/card.ts, src/models/interface/ICard.ts
**우선순위**
D-1
**변경사항**
- closes: #56 
- 이슈 참조
**유의사항**
**참조**
=> [FIX] 카드 스키마에 북마크한 유저리스트 추가

src/controllers/userController.ts, src/intefaces/user/UserBookmarkDto.ts, src/intefaces/user/UserBookmarksDto.ts, src/modules/responseMessage.ts, src/routes/userRouter.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
* close #52 
* 북마크 조회 API 구현
**유의사항**
**참조**
=> [FEAT] 북마크 조회 API 구현

.eslintrc.json, src/controllers/CategoryController.ts, src/controllers/ballotController.ts, src/controllers/index.ts, src/controllers/userController.ts, src/index.ts, src/intefaces/CardResponseDto.ts, src/intefaces/exception.ts, src/loaders/db.ts, src/middlewares/auth.ts, src/middlewares/errorHandler.ts, src/models/bookmark.ts, src/models/card.ts, src/models/interface/IBookmark.ts, src/models/interface/ICard.ts, src/routes/ballotRouter.ts, src/services/CategoryService.ts, src/services/ballotService.ts, src/services/index.ts, src/services/userService.ts, src/types/TypedRequest.ts
**우선순위**
D-0
**변경사항**
- closes: #59
- Request를 TypedRequest로 변경했습니다
**유의사항**
- 의문점 1. express 에서 전역으로 request 에 user를 추가했지만 코드에서 user의 타입을 모르더라구요.
- 그래서 결국 `user as Types.ObjectId` 로 할당해줬습니다.
```typescript
// express.d.ts
type User = {
id: Types.ObjectId;
};
declare namespace Express {
export interface Request {
user: User;
}
}
```
**참조**
=> [FIX] 북마크 스키마 추가 및 빌드 에러 해결

.github/workflows/ci.yml, package.json, src/config/multer.ts, src/config/s3Client.ts
**우선순위**
D-0
**변경사항**
- closes: #47 
**유의사항**
- 기존의 build 커맨드는 `build-run` 으로 대체 했습니다
**참조**
=> [FEAT] ci script

src/controllers/ballotController.ts, src/controllers/userController.ts, src/intefaces/user/UserBookmarkInfo.ts, src/loaders/db.ts, src/middlewares/flexibleAuth.ts, src/models/ballotResult.ts, src/modules/responseMessage.ts, src/modules/util.ts, src/routes/ballotRouter.ts, src/routes/userRouter.ts, src/services/ballotService.ts, src/services/userService.ts
**우선순위**
D-1
**변경사항**
* close #13 
**유의사항**
* 하드코딩한거 죄송합니다. 수정하겠습니다 ㅜ
* 메소드 분리
* 어색한 네이밍 수정
**참조**
=> [FEAT] 투표 현황 조회 API

package-lock.json, package.json, src/index.ts
**우선순위**
D-0
**변경사항**
* close #68 
**유의사항**
**참조**
=> [CHORE] CORS 설정

src/index.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> [HOTFIX] CORS 설정 수정

src/loaders/db.ts, src/models/category.ts, src/models/interface/ICategory.ts, src/services/CategoryService.ts
**우선순위**
D-
**변경사항**
웹에서 요구한 랜덤하게 섞기 및 imgurl로 수정
**유의사항**
**참조**
=> [HOTFIX] 카테고리 조회 수정

src/services/ballotService.ts
**우선순위**
D-0
**변경사항**
* close #73 
* 투표 현황조회에 투표 제목이 반환이 안돼서 추가해줬습니다.
**유의사항**
**참조**
=> [HOTFIX] 투표 현황 조회시 투표 제목 반환 추가 

src/models/category.ts, src/models/interface/ICategory.ts, src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
이제 카테고리 조회 시에 content도 같이 보입니다.
**유의사항**
**참조**
=> [FIX] 카테고리 조회 수정

src/controllers/cardController.ts, src/routes/cardRouter.ts
**우선순위**
D-0
**변경사항**
**유의사항**
- 베스트 피클 5개 보는거 없앰
- 알아서 보쇼
**참조**
=> [FIX] read best piickles

src/middlewares/auth.ts, src/middlewares/flexibleAuth.ts
**우선순위**
D-0
**변경사항**
- closes: #81 
-  flexibleAuth 에서는 jwt 형식 이상할 경우 없는것으로 간주합니당
**유의사항**
**참조**
=> [FIX] 토큰 형식 잘못된 경우 없는 것으로 간주

src/controllers/ballotController.ts, src/services/ballotService.ts
**우선순위**
D-0
**변경사항**
이제 배열이 비어있는 걸 보내줍니다!
**유의사항**
**참조**
=> [FIX] ballot에서 빈 배열 보내주기

src/controllers/CategoryController.ts, src/controllers/cardController.ts, src/intefaces/CardResponseDto.ts, src/routes/CategoryRouter.ts, src/routes/cardRouter.ts, src/services/CategoryService.ts, src/services/cardService.ts
**우선순위**
D-0
**변경사항**
* close #76 
**유의사항**
**참조**
=> [HOTFIX] 카드 북마크 여부 반환

src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
카드 필터를 거치고 조회 할 때 섞어서 조회합니다.
**유의사항**
**참조**
=> [FIX] 카드 랜덤 조회

src/controllers/cardController.ts, src/services/cardService.ts
**우선순위**
D-0
**변경사항**
- 베스트 피클 조회할 때 북마크 있는 애들 형식이 잘못나와서 프론트에서 타입에러 난다함
- 보니까 내가 find projection을 잘못 설정해줬네
**유의사항**
- 없
- 어푸루부해도!
**참조**
=> [HOTFIX] 베스트피클 잘못된 형식 수정

src/modules/jwtHandler.ts
**우선순위**
D-0
**변경사항**
* jwt 유효 시간 365d 로 수정
**유의사항**
**참조**
=> [HOTFIX] jwt 토큰 유효시간 수정

src/intefaces/user/UserBookmarkDto.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
* close #96 
**유의사항**
**참조**
=> [HOTFIX] 마이피클 조회 필드값 수정

src/services/ballotService.ts
**우선순위**
D-0
**변경사항**
* 투표 항목 조회 로직 수정
* close #98 
**유의사항**
**참조**
=> [HOTFIX] 투표 항목 조회 로직 수정

src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
카테고리 조회를 __v값에 맞추어 정렬시켰습니다.
**유의사항**
**참조**
=> [FIX] 순서대로 카테고리 보이게 수정

src/services/ballotService.ts
**우선순위**
D-0
**변경사항**
* close #104 
* 투표 현황 조회 수정
* 투표 하기 -> 투표 하기, 삭제, 수정으로 변경
**유의사항**
**참조**
=> [HOTFIX] 투표 현황 조회 필드값 수정

src/index.ts
**우선순위**
D-0
**변경사항**
**유의사항**
**참조**
=> [FEAT] health check api

src/intefaces/CategoryInfoDto.ts, src/services/CategoryService.ts
**우선순위**
D-
**변경사항**
그냥 나오는 거 섞었습니다.
**유의사항**
**참조**
=> [FIX] 카테고리에 있는 카드 랜덤하게 조회

src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
- closes: #110 
- 로그인 하지 않은 경우 연산하지 않도록 수정
- 모든 카드 아이디를 파라미터로 북마크 컬렉션 조회 연산이 한번만 이뤄지도록 수정
**유의사항**
- 다들 요청 쏴보세염
**참조**
=> [HOTFIX] 북마크 여부 확인 로직 변경

src/services/userService.ts
**우선순위**
D-0
**변경사항**
북마크 전부 삭제되는 오류 수정
**유의사항**
**참조**
=> [FIX] 북마크 삭제 시 전부 삭제되는 문제 수정

.husky/pre-commit, package.json, src/controllers/userController.ts, src/modules/util.ts, src/services/ballotService.ts, src/services/userService.ts, test/user.spec.ts
**우선순위**
D-1
**변경사항**
- resolve: #115 
- 투표결과 조회 로직 수정
- 그리고 자꾸 테스트 실패하길래 .. 여유 있어질 때까지 test 훅을 없애놓을까 합니다.
- mongoose 는 디폴트 커넥션을 하나로만 정할 수 있어서 test db는 createConnection 써서 연결시켜줄까 했어요
- 동현 구해줘..
**유의사항**
**참조**
=> [HOTFIX] 투표결과 조회 로직

.github/workflows/build-and-push.yml, src/controllers/userController.ts, src/intefaces/exception.ts, src/routes/userRouter.ts, src/services/authService.ts, src/services/userService.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> [CHORE] 빌드 후 업로드

src/controllers/userController.ts, src/intefaces/PostBaseResponseDto.ts, src/intefaces/createUserCommand.ts, src/intefaces/user/UpdateUserDto.ts, src/intefaces/user/UserProfileResponseDto.ts, src/models/interface/IUser.ts, src/models/user.ts, src/modules/responseMessage.ts, src/modules/util.ts, src/routes/userRouter.ts, src/services/userService.ts
**우선순위**
D-1
**변경사항**
나중에 .......... 프로필 조회 시 name 필드 없애자
이제 유저 스키마에 name 필드 없는데, 이전에 프로필 조회 api에서 name을 응답 dto에 포함하고 있어서,
dto 인터페이스에서 필드를 지울까 생각했었는데, 그러면 지금 돌아가고 있는 웹 앱에서 에러가 날거라 그러지는 않고 '김피클'이라는 더미값을 설정해주었습니다.
없애려면 웹한테 미리 얘기해서 반영해달라고 부탁해야합니다
근데 이상한건 와프 봐도 이 값을 아무데서도 사용하지 않는 다는 것.. 뭐냐 대체
이번 릴리즈를 통해 변경되는 api들을 보며 환경별 서버가 따로 존재해야함을 다시 한번 깨달았다
근데 그럴 돈이 어딨.나요?.
**유의사항**
제가 좀 졸립니다
**참조**
=> [FEAT] new 회원가입

src/config/index.ts, src/controllers/userController.ts
**우선순위**
D-0
**변경사항**
임시로 설정해뒀던 url 바꿨음
지영이 짱~
**유의사항**
- 프로덕션 배포 시 env 설정 값 바꿔줘야함
dev.piickle.link -> www.piickle.link
**참조**
https://w1655692613-dsw141740.slack.com/archives/C03L7G0U3QV/p1662911601720379
=> [CHORE] 인증메일 리디렉션 url 설정

src/controllers/userController.ts, src/intefaces/createUserCommand.ts, src/routes/userRouter.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
- 비즈니스 로직 상 회원가입이 완료되지 않은 경우에 토큰을 사용하는 것이 옳지 않다는 웹피클들의 생각에 동의해서 합쳐놓았습니당!
- 헤헤. 다들 수고가 많군요
**유의사항**
**참조**
=> [FIX] 회원가입 통합

.eslintrc.json, src/config/index.ts, src/routes/index.ts, src/routes/testRouter.ts
@NYeonK @NaveOWO 
관리자가 사용할 API입니다
인증처리 하고자 하는 email 인증시켜드림
https://www.notion.so/f03cbe155bb44a7981fa34fe98633a5e
지우고자 하는 email 지워드림
https://www.notion.so/a455c81522d841eba1a3dd02112cc59a
key와 함꼐 보내주세요.
=> [FEAT] 개발용 회원 관련 api 

src/middlewares/auth.ts, src/modules/returnToSlack.ts
=> [CHORE] added token to slack error message

src/controllers/userController.ts, src/loaders/db.ts, src/models/quitLog.ts, src/routes/userRouter.ts, src/services/userService.ts
- 까먹고 탈퇴사유 만드는 걸 안해서 추가했음
- 요청에 바디가 필요해지므로 PUT 메서드로 변경해주었음
=> [FEAT] 탈퇴 사유 기록

src/controllers/userController.ts, src/middlewares/errorHandler.ts, src/models/quitLog.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
- 탈퇴 기록 스키마의 탈퇴 사유 프로퍼티를 수정했으요
- `reason` 문자열 -> `reasons` 배열
- 탈퇴 사유 enum으로 만들어봄
**유의사항**
- enum 도입하긴 했는데 DB에 value로 저장돼요
**참조**
[api 문서](https://www.notion.so/API-a2efdef81ae34b9c98bcf0d96cd5dd4f)
=> [FIX] 탈퇴 사유는 여러 개가 될 수 있다

src/services/cardService.ts
**우선순위**
D-
**변경사항**
임시로 카드 제목만 수정
**유의사항**
**참조**
=> [HOTFIX] 베스트 카드 변경

src/controllers/CategoryController.ts, src/controllers/ballotController.ts, src/controllers/cardController.ts, src/intefaces/exception.ts, src/loaders/db.ts, src/middlewares/auth.ts, src/middlewares/errorHandler.ts, src/models/bestCard.ts, src/models/card.ts, src/modules/returnToSlack.ts, src/services/CategoryService.ts, src/services/ballotService.ts, src/services/cardService.ts, src/types/types.d.ts
**우선순위**
D-1
**변경사항**
- 보니까 카드 변경될 때마다 코드 바꾸는 건 아닌 것 같아 그냥 데이터베이스에 저장하는 방식으로 바꿔봤어요
- 아까는 급해서 바뀐 주제로 텍스트를 수정해놨는데요, 앞으로 관리자들이 직접 수정할 수 있게 하려면 데이터베이스에 옮기는게 피할 수 없는 일일 것 같아요! 기반 작업으로 컬렉션 생성, 스키마 정의를 해두었다고 생각해주세요
**유의사항**
- 코멘트 봐주세요
**참조**
=> [FEAT] 베스트 카드 저장 위치 변경

src/config/index.ts, src/controllers/userController.ts, src/routes/userRouter.ts, src/services/authService.ts
**우선순위**
D-0
**변경사항**
- QA랑 프로덕션에서 같은 리디렉션 아이디로 향하는 것을 고쳐주었어요
- 파이어베이스 기본 링크를 사용, 동적 링크로 원하는 환경의 리디렉션 url을 설정합니다
**유의사항**
- 이거 머지되면 env도 고쳐줘야되고
- 파이어베이스 템플릿 링크도 바꿔줘야해요
- 하.... 근데 지금은 파이어베이스 처리율 제한에 걸려서 잘 되는지 확인을 못했요..ㅜ
**참조**
https://w1655692613-dsw141740.slack.com/archives/C03L7G0U3QV/p1664861626815479
=> [FEAT] 이메일 인증  dev/prod 환경 구분

src/models/user.ts, src/services/userService.ts
**우선순위**
D-0
**변경사항**
회원가입 서비스 로직에서 메일 인증 여부 검사 로직을 제거 했습니다.
**유의사항**
- 급한대로 사용하지 않는 소스 코드를 제거하지는 않았습니다
**참조**
[과정 설명 슬랙](https://w1655692613-dsw141740.slack.com/archives/C04FGQCL894/p1672750264294299)
=> [FIX] 메일 인증 여부 확인 로직 제거

src/controllers/userController.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> [HOTFIX] path variable로 읽고 있는 변수 수정

src/services/CategoryService.ts
- 카드 랜덤 조회 방식을 변경했어요
- 이제 같은 카드를 섞어서 주는 방식이 아닌 모든 카드 중 원하는 양 만큼 랜덤하게 뽑아 주어요
=> [FIX] 카드 랜덤 조회 기능

src/models/category.ts, src/models/interface/ICategory.ts, src/services/CategoryService.ts
**우선순위**
D-0
**변경사항**
- api 응답에 카테고리별 유니코드 추가함요
**유의사항**
- 우린 언제까지 이 코드로 연명하게 될까요
**참조**
=> [FEAT] 카테고리에 유니코드 추가

.github/CODEOWNERS, src/models/ballotTopic.ts, src/models/interface/IBallotTopic.ts, src/services/ballotService.ts
**우선순위**
D-1
**변경사항**
- 투표 주제 스키마가 변경되었습니다
- rdb로 마이그레이션 시 id로 사용할 값이기 때문에 신경 안쓰셔도 돼염
**유의사항**
**참조**
=> Feat/투표주제 스키마 유니크키 추가

src/intefaces/CardMedleyDto.ts, src/intefaces/CardMedleyPreviewDto.ts, src/models/cardMedley.ts, src/models/interface/ICardMedley.ts, src/services/cardMedleyService.ts
**우선순위**
D-0
**변경사항**
- fix 에 가깝기도 한 것 같음
- 이럴거면 진짜 저희도 이미지로 고정하는거 어떨지 정말 생각해봐야합니다. ~~넷플릭스..~~
**유의사항**
**참조**
=> [FEAT] 카드 메들리에 커버타이틀 추가

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml, src/controllers/cardController.ts, src/controllers/userController.ts, src/index.ts, src/loaders/db.ts, src/middlewares/flexibleAuth.ts, src/modules/util.ts, src/services/ballotService.ts, src/services/cardService.ts, src/services/userService.ts, test/user.spec.ts
**우선순위**
D-1
**변경사항**
- 메인화면 베스트 피클 조회 방식
- 메인화면 투표 주제 조회 방식
- 일단 해당 유저 투표 여부와 관계 없이 가도록 했습니다
- null을 가려내기 위해.. Arrays.filter에서 사용할 isNotEmpty라는 함수를 만들어서 사용해보았습니다
- 여러 스키마에 다 쓰고 싶어서 제네릭으로 둠
- 불필요한 콘솔로그가 있길래 지웠어요 
**유의사항**
- 아 저희 액션 러너 삭제했잖아용, 그래서 배포 스크립트에서 러너 실행하는 부분 급하게 주석처리 해놨습니다. ..
- 저 진짜 너무 졸려요
**참조**
https://w1655692613-dsw141740.slack.com/archives/C04FGQCL894/p1679635585462519
=> [REFACTOR] 홈화면 인기 주제 산출 방식

src/services/cardService.ts
**우선순위**
D-1
**변경사항**
limit 로직 수정하고
정렬 조건에 _id  desc를 추가했습니다.
**유의사항**
**참조**
=> [FIX] 카드 개수 limit 로직 수정

src/models/ballotItem.ts, src/models/interface/IBallotItem.ts, src/services/ballotService.ts
**우선순위**
D-0
**변경사항**
- 왜 이게 누락됐는지는 모르겠지만 누락돼서 다시 추가합니당
**유의사항**
**참조**
=> [FIX] 누락된 필드 추가

src/models/ballotItem.ts, src/models/interface/IBallotItem.ts, src/services/ballotService.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> [HOTFIX] 투표 조회 누락 필드 추가

src/index.ts, src/middlewares/session/guestHandler.ts, src/middlewares/session/uidSetter.ts, src/routes/index.ts, src/types/express.d.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> [FIX] uid setter

src/config/index.ts, src/index.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> [FIX] fix cors origin

src/config/index.ts, src/index.ts
**우선순위**
D-
**변경사항**
**유의사항**
env 변수 추가함
`WEB_HOST` 랑 `DEV_WEB_HOST`
**참조**
우울.. > https://w1655692613-dsw141740.slack.com/archives/C04NGLXFXMF/p1682870039700079
=> [FIX] dev web origin 설정

src/config/index.ts, src/index.ts
**우선순위**
D-
**변경사항**
.env 추가 ACCESS_CONTROL_ALLOW_ORIGIN_PORT 
**유의사항**
**참조**
=> [fix] cors 포트 추가 .env 추가

src/config/index.ts, src/index.ts
**우선순위**
#163 
D-
**변경사항**
로컬용 cors 추가
**유의사항**
**참조**
=> [FEAT] 로컬용 cors 추가

src/config/index.ts, src/index.ts
**우선순위**
D-0
**변경사항**
cors origin을 하나의 변수로 관리합니다.
구분자도 변수로 관리합니다.
**유의사항**
**참조**
=> fix: allow origin을 하나의 변수로 관리

src/services/ballotService.ts
**우선순위**
D-0
**변경사항**
다시 투표하기 버그 고칩니다
**유의사항**
제가 바로 고쳤더군요.. 예외처리가 최선의 답이라 생각했으나
이미 API가 쓰이고 있으니 호환되도록 리팩터링했습니다
**참조**
=> [HOTFIX] 같은 항목으로 다시 투표하는 기능

src/services/ballotService.ts
**우선순위**
**변경사항**
- 재투표는 삭제처리 하는 기존로직을 되돌렸습니다
- 왜 .. 이렇게 짰냐고 물어보면 기억 안나겠지
- 나중에 꼭 프론트엔드 설득해서 API 개편하자
- closed: #178 
**유의사항**
**참조**
=> [HOTFIX] 같은 항목으로 다시 투표하기

src/controllers/userController.ts, src/loaders/db.ts, src/models/blockedCard.ts, src/models/interface/IBlockedCard.ts, src/modules/responseMessage.ts, src/routes/userRouter/index.ts, src/routes/userRouter/userCardRouter.ts, src/services/blockCardService.ts, src/services/index.ts
**우선순위**
D-1
**변경사항**
- 블랙리스트 추가 삭제 기능을 추가했어요
**유의사항**
- 이후 작업할 때도 베이스 브랜치를 꼭 **`sprint/4th`** 로 해주세요!!!
- 꼭! 관련한 이야기는 한번 더 논의해봅시다
**참조**
=> [FEAT] 카드 블랙리스트 추가/삭제

src/controllers/userController.ts, src/services/socialAuthService.ts
**우선순위**
D-
**변경사항**
- closes: #181 
**유의사항**
- 코드가 깔끔하지 못한 것 같아요 (언제나 그랬지만)
**참조**
=> [FEAT] 소셜로그인 응답에 가입 여부 추가

src/models/socialVendor.ts, src/services/dto/KakaoResponse.ts, src/services/dto/NaverResponse.ts
**우선순위**
D-0
**변경사항**
- 유저가 인증서버에 제공 비동의 했을 때 닉네임 임의로 지정해줍니다.
**유의사항**
- 나중에 랜덤 생성해서 적절한 길이로 지정을 해주는 편이 나을 것 같습니다. 왜냐면 너무 긴 경우가 있어서 ui 를 헤치는 경우도 있고, 그냥 별로인 것 같습니다.
**참조**
=> [HOTFIX] 닉네임이 없을 경우 임의로 지정

src/services/CategoryService.ts, src/services/cardService.ts
**우선순위**
D-
**변경사항**
* 기존의 기능인 필터별, 카테고리별, 공유 받은 카드 조회 시 유저의 블랙리스트로 등록 된 카드가 조회되지 않도록 기능을 추가 했습니다.
**유의사항**
* map 써서 ObjectId만 가져오고 싶었는데 자꾸 이중 배열이 돼서 for 문으로 list에 넣어줬는데 이부분 좀 더 효율적으로 바꿀 수 있는 방법이 있을까...?
**참조**
* 구현하다가 순간 ctm 버튼 눌렀을때 요청되는 API가 뭔지 기억이 안나서 웹 코드 까지 보고 왔다링,,,
* 테스트를 내 계정으로 모든 카드 블랙리스트 등록해두고 로그인/ 비로그인 시 카드 조회 여부로 확인함!
=> [FEAT] 블랙리스트 제외 카드 조회

src/controllers/userController.ts, src/intefaces/createUserCommand.ts, src/models/user/ageGroup.ts, src/routes/userRouter/index.ts, src/services/dto/KakaoResponse.ts, src/services/dto/NaverResponse.ts, src/services/userService.ts
**우선순위**
D-2
**변경사항**
회원가입 기능에서 생일을 연령대로 변경했습니다
**유의사항**
**참조**
=> [FEAT] 회원가입 기능 연령대 반영

src/controllers/userController.ts, src/intefaces/createUserCommand.ts, src/models/user/gender.ts
**우선순위**
D-0
**변경사항**
- 회원가입 요청에 성별 입력이 선택일 수 있도록 변경
**유의사항**
- 딱히 없음
**참조**
=> [HOTFIX] 요청에서 성별을 선택으로 변경

src/services/cardService.ts
**우선순위**
D-
**변경사항**
* 기존의 카드 조회 API에 랜덤이 적용되지 않아 수정하였습니다.
**유의사항**
**참조**
=> [HOTFIX] 카드 조회시 랜덤 조회로 수정

src/loaders/db.ts, src/models/mind23/comment.ts, src/models/mind23/prizeEntry.ts, src/models/mind23/question.ts
**우선순위**
D-1
**변경사항**
- closes: #201 
**유의사항**
**참조**
=> feat: 스키마 구성

src/config/index.ts, src/middlewares/cors.ts
**우선순위**
D-0
**변경사항**
origin 적용을 하지 않아서..... ㅇ^ㅇ......
**유의사항**
**참조**
=> fix: cors origin

src/controllers/mind23Controller.ts, src/intefaces/mind23/CommentDto.ts, src/models/mind23/prizeEntry.ts, src/services/mind23Service.ts
**변경사항**
* 경품응모 스키마에 알림 여부 추가
* 본인 댓글 여부 추가
* 댓글 닉네임 8자 제한
**유의사항**
**참조**
=> [HOTFIX] 당일용 프로덕트 댓글 관련 API 수정

src/intefaces/mind23/Mind23CardResponseDto.ts, src/services/mind23Service.ts
**변경사항**
* 변경된 사안으로 인해 질문 조회시 필수 질문 여부를 제거 하였습니다.
**유의사항**
**참조**
=> [HOTFIX] 질문 조회 esstional 값 제거 

src/services/cardService.ts
**우선순위**
D-
**변경사항**
**유의사항**
**참조**
=> Release 2.1.1 최근 북마크 조회 버그 수정

.github/workflows/build.yml, .github/workflows/deploy-production.yml
**우선순위**
D-0
**변경사항**
- main에 hotfix로 반영되는 것이 develop에 반영되면 좋겠어요
- 잘 됩니다. 자동으로 머지되는 것이 아니라 충돌을 해결할 수 있어 더 좋은 것 같습니다 :D
**유의사항**
**참조**
=> feat: added workflow for syncing branches

src/services/mind23Service.ts
**우선순위**
D-0
**변경사항**
- 탈퇴한 회원이 남긴 댓글이 있을 경우 예외를 처리하지 않는 버그를 수정했습니다.
**유의사항**
- 없어요
**참조**
=> hotfix: handle deleted author
